name: "Stonks Overwatch"
services:
  web:
    build: .
    image: stonks-overwatch
    command: ["sh", "/app/init.sh"]
    volumes:
      - ./src/:/app/src/
      - ./data/:/app/data/
    ports:
      - "8000:8000"
