name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run common actions
        uses: ./.github/actions/common-action
      - name: Run lint check
        run: |
          make lint-check
      - name: Markdown Check
        run: |
          make markdown-check

  test:
    name: Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run common actions
        uses: ./.github/actions/common-action
      - name: Run tests
        run: |
          poetry run pytest

#  FIXME: The GitHub Action is failing. Lets do it local until it can be fixed
#  analyze:
#    runs-on: ubuntu-latest
#    permissions:
#      # Required for all workflows
#      security-events: write
#      # Only required for workflows in private repositories
#      actions: read
#      contents: read
#    steps:
#      - name: Perform Bandit Analysis
#        uses: PyCQA/bandit-action@v1
#        with:
#          configfile: 'pyproject.toml'
