name: Release

on:
  workflow_dispatch:  # Allows manual trigger for any branch

# Cancel active CI runs for a PR before starting another run
concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  FORCE_COLOR: "1"

defaults:
  run:
    shell: bash

jobs:
  package:
    name: Create Installers
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target: [ "flatpak", "deb", "rpm" ]
        include:
          - target: "flatpak"
            platform: "Linux"
            output-format: "Flatpak"
            runs-on: "ubuntu-latest"
            pre-command: "sudo apt update && sudo apt -y install flatpak flatpak-builder"
            briefcase-run-prefix: "xvfb-run"

          - target: "deb"
            platform: "Linux"
            output-format: "system"
            runs-on: "ubuntu-latest"
            pre-command: "sudo apt -y install socat"
            briefcase-run-prefix: "xvfb-run"
            briefcase-args: "--target ubuntu:24.04"

          - target: "rpm"
            platform: "Linux"
            output-format: "system"
            runs-on: "fedora-latest"
            pre-command: "sudo apt -y install socat"
            briefcase-run-prefix: "xvfb-run"
            briefcase-args: "--target fedora:40"

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run common actions
        uses: ./.github/actions/common-action

      - name: Install Briefcase
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install briefcase
          python -m pip install toml-cli

      - name: Setup Environment
        run: |
          ${{ matrix.pre-command }}

      - name: Collect Static Files
        run: |
          # Collect static files for the app
          make collectstatic

      - name: Build App for ${{ matrix.target }}
        run: |
          ${{ matrix.briefcase-build-prefix }} \
          briefcase build \
            ${{ matrix.platform || matrix.target }} \
            ${{ matrix.output-format }} \
            --test --no-input --log \
            ${{ matrix.briefcase-args }} \
            ${{ matrix.briefcase-build-args }}
      #
      #      - name: Test App
      #        run: |
      #          ${{ matrix.briefcase-run-prefix }} \
      #          briefcase run \
      #            ${{ matrix.platform || matrix.target }} \
      #            ${{ matrix.output-format }} \
      #            --test --no-input --log \
      #            ${{ matrix.briefcase-args }} \
      #            ${{ matrix.briefcase-run-args }}

      - name: Package App for ${{ matrix.target }}
        run: |
          ${{ matrix.briefcase-package-prefix }} \
          briefcase package \
            ${{ matrix.platform || matrix.target }} \
            ${{ matrix.output-format }} \
            --update --adhoc-sign --no-input --log \
            ${{ matrix.briefcase-args }} \
            ${{ matrix.briefcase-package-args }}

      - name: Upload App
        if: ${{ !env.ACT }}
        # Briefcase cannot create iOS artifacts; instead, apps
        # must be packaged and published for iOS through Xcode.
        uses: actions/upload-artifact@v5
        with:
          name: Stonks-Overwatch-${{ matrix.target }}
          path: dist
          retention-days: 5
          if-no-files-found: error
