name: pre-commit autoupdate

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run common actions
        uses: ./.github/actions/common-action
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit autoupdate script
        run: bash .github/scripts/update_precommit_hooks.sh
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: autoupdate pre-commit hooks'
          branch: pre-commit-autoupdate
          create_branch: true
          push_options: '--force'
