name: pre-commit autoupdate

on:
  schedule:
    - cron: '0 3 * * 1' # Every Monday at 03:00 UTC
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run common actions
        uses: ./.github/actions/common-action
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit autoupdate script
        run: bash .github/scripts/update_precommit_hooks.sh
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Create or checkout pre-commit-autoupdate branch
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git checkout -b pre-commit-autoupdate || git checkout pre-commit-autoupdate
          git reset --hard origin/main
      - name: Push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: autoupdate pre-commit hooks'
          push_options: '--force'
