name: pre-commit autoupdate

on:
  schedule:
    - cron: '0 3 * * *' # Every day at 03:00 UTC
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run common actions
        uses: ./.github/actions/common-action
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit autoupdate script
        run: pre-commit autoupdate
      - name: Check for changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in the repository"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in the repository"
          fi
      - name: Create Pull Request
        if: steps.check-changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          # The token must have the next permissions:
          #  Fine=grained permissions:
          #   - Contents: Read and write,
          #   - Pull requests: Read and write
          #   - Workflows: Read and write (may be not required)
          token: ${{ secrets.PAT_TOKEN }}
          title: 'chore: autoupdate pre-commit hooks'
          body: |
            This PR updates pre-commit hooks to their latest versions.

            Changes made by `pre-commit autoupdate`.

            Please review the changes before merging.
          branch: chore/autoupdate-pre-commit-hooks
          commit-message: 'chore: autoupdate pre-commit hooks'
          delete-branch: true
